import { httpConfig } from "app/mock-api/common/http/config";

// should be minified
export const Runtimefields = {"runtime_mappings":{"Empresa":{"type":"keyword","script":{"source":"emit(doc['tenant'].value);"}},"Actividade":{"type":"keyword","script":{"source":"emit(doc['activity'].value);"}},"TipoArtigoServicoNome":{"type":"keyword","script":{"source":"def type  = doc['TipoArtigoServico'].value;\r\nif(type == 'A'){\r\nemit('Artigo')\r\n}\r\nelse {\r\nemit('Serviço')\r\n}"}}}};


// should be minified
export const RequestsArr = [
  {"ValorLiquidoVenda":{"aggs":{"2":{"terms":{"field":"_DimensionVariable","order":{"1":"desc"},"size":"_TopVariable"},"aggs":{"1":{"sum":{"field":"ValorLiquidoVendaEUR"}},"3":{"sum":{"field":"ValorMargemEUR"}}}}},"size":0,"fields":[{"field":"created_date_time","format":"strict_date_time"},{"field":"date","format":"date_time"}],"script_fields":{},"stored_fields":["*"],"runtime_mappings":Runtimefields.runtime_mappings,"_source":{"excludes":[]},"query":{"bool":{"must":[],"filter":[{"match_phrase":{"resource_type":"vendas"}},{"range":{"date":{"format":"strict_date_optional_time","gte":"2022-01-01T00:00:00.000Z","lte":"2022-09-08T13:30:55.013Z"}}}],"should":[],"must_not":[]}}}},
  {"ValorMargem":{"aggs":{"2":{"terms":{"field":"_DimensionVariable","order":{"1":"desc"},"size":"_TopVariable"},"aggs":{"1":{"sum":{"field":"ValorMargemEUR"}},"3":{"sum":{"field":"ValorMargemEUR"}}}}},"size":0,"fields":[{"field":"created_date_time","format":"strict_date_time"},{"field":"date","format":"date_time"}],"script_fields":{},"stored_fields":["*"],"runtime_mappings":Runtimefields.runtime_mappings,"_source":{"excludes":[]},"query":{"bool":{"must":[],"filter":[{"match_phrase":{"resource_type":"vendas"}},{"range":{"date":{"format":"strict_date_optional_time","gte":"2022-01-01T00:00:00.000Z","lte":"2022-09-08T13:30:55.013Z"}}}],"should":[],"must_not":[]}}}},
  {"QuantidadeVenda":{"aggs":{"2":{"terms":{"field":"_DimensionVariable","order":{"1":"desc"},"size":"_TopVariable"},"aggs":{"1":{"sum":{"field":"QuantidadeVenda"}},"3":{"sum":{"field":"ValorMargemEUR"}}}}},"size":0,"fields":[{"field":"created_date_time","format":"strict_date_time"},{"field":"date","format":"date_time"}],"script_fields":{},"stored_fields":["*"],"runtime_mappings":Runtimefields.runtime_mappings,"_source":{"excludes":[]},"query":{"bool":{"must":[],"filter":[{"match_phrase":{"resource_type":"vendas"}},{"range":{"date":{"format":"strict_date_optional_time","gte":"2022-01-01T00:00:00.000Z","lte":"2022-09-08T13:30:55.013Z"}}}],"should":[],"must_not":[]}}}}
];

export const RequestsArrOthers = [
  {"ValorLiquidoVenda":{"aggs":{"other-filter":{"aggs":{"1":{"sum":{"field":"ValorLiquidoVendaEUR"}},"3":{"sum":{"field":"ValorMargemEUR"}}},"filters":{"filters":{"f":{"bool":{"must":[],"filter":[],"should":[],"must_not":[]}}}}}},"size":0,"fields":[{"field":"created_date_time","format":"strict_date_time"},{"field":"date","format":"date_time"}],"script_fields":{},"stored_fields":["*"],"runtime_mappings":Runtimefields.runtime_mappings,"_source":{"excludes":[]},"query":{"bool":{"must":[],"filter":[{"match_phrase":{"resource_type":{"query":"vendas"}}},{"range":{"date":{"format":"strict_date_optional_time","gte":"2022-01-01T00:00:00.000Z","lte":"2022-09-09T18:24:20.723Z"}}}],"should":[],"must_not":[]}}}},
  {"ValorMargem":{"aggs":{"other-filter":{"aggs":{"1":{"sum":{"field":"ValorMargemEUR"}},"3":{"sum":{"field":"ValorMargemEUR"}}},"filters":{"filters":{"f":{"bool":{"must":[],"filter":[],"should":[],"must_not":[]}}}}}},"size":0,"fields":[{"field":"created_date_time","format":"strict_date_time"},{"field":"date","format":"date_time"}],"script_fields":{},"stored_fields":["*"],"runtime_mappings":Runtimefields.runtime_mappings,"_source":{"excludes":[]},"query":{"bool":{"must":[],"filter":[{"match_phrase":{"resource_type":{"query":"vendas"}}},{"range":{"date":{"format":"strict_date_optional_time","gte":"2022-01-01T00:00:00.000Z","lte":"2022-09-09T18:24:20.723Z"}}}],"should":[],"must_not":[]}}}},
  {"QuantidadeVenda":{"aggs":{"other-filter":{"aggs":{"1":{"sum":{"field":"QuantidadeVenda"}},"3":{"sum":{"field":"ValorMargemEUR"}}},"filters":{"filters":{"f":{"bool":{"must":[],"filter":[],"should":[],"must_not":[]}}}}}},"size":0,"fields":[{"field":"created_date_time","format":"strict_date_time"},{"field":"date","format":"date_time"}],"script_fields":{},"stored_fields":["*"],"runtime_mappings":Runtimefields.runtime_mappings,"_source":{"excludes":[]},"query":{"bool":{"must":[],"filter":[{"match_phrase":{"resource_type":{"query":"vendas"}}},{"range":{"date":{"format":"strict_date_optional_time","gte":"2022-01-01T00:00:00.000Z","lte":"2022-09-09T18:24:20.723Z"}}}],"should":[],"must_not":[]}}}}
]